name: Verify Telemachus Datasets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pandas pyarrow

      - name: Verify all datasets with repo script
        run: |
          chmod +x scripts/verify.py
          python scripts/verify.py --all